use_frameworks!

platform :ios, '8.0'

target 'LWPhotoPicker_Example' do
  pod 'LWPhotoPicker', :path => '../'

  pod 'Masonry','1.1.0'
  pod 'SDWebImage', '5.4.0'

  # target 'LWPhotoPicker_Tests' do
  #   inherit! :search_paths
  #
  # end
end
