use_frameworks!

platform :ios, '8.0'

target 'libPhotoPicker_Example' do
  pod 'libPhotoPicker', :path => '../'

  pod 'Masonry','1.1.0'
  pod 'SDWebImage', '~> 5.0'

  # target 'libPhotoPicker_Tests' do
  #   inherit! :search_paths
  #
  # end
end
