source 'https://gitlab.com/ioslibraries1/mygitlabrepo.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'LWPhotoPicker_Example' do
  pod 'LWPhotoPicker', :path => '../'

  pod 'Masonry'
  pod 'YYCache'

  # target 'LWPhotoPicker_Tests' do
  #   inherit! :search_paths
  #
  # end
end
